version: '3.1'

services:

  php-fpm:
    build: docker
    container_name: 'php_bthlaravel'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx_bthlaravel'
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:11
    ports:
      - 15431:5432
    container_name: 'postgresql_bthlaravel'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'bthlaravel'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
